core/urls.py
from django.urls import path, include
from core import views

app_name ="core"

urlpatterns = [
   path('', views.index, name='index'),
   path('products/', views.product_list_view, name='product-list'),
   path('categories/', views.category_list_view, name='category-list'),
   path('category_product/<cid>/', views.category_product_list, name='category-product-list'),
   path('vendor_list/', views.vendor_list_view, name="vendor-list"),
   path('product_detail/<pid>/', views.product_detail_view, name='product-detail'),
   path('product/tags/<slug:tag_slug>/', views.tag_list, name='tags'),
   path('ajax-add-review/<int:pid>/', views.ajax_add_review, name="ajax-add-review"),
   path('search/', views.search_view, name='search'),
   path('filter-products/', views.filter_product, name="filter-products"),
   path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
   path('cart/', views.cart_view, name="cart"),
   path('delete-from-cart/', views.delete_item_from_cart, name="delete-from-cart"),
   path('update-from-cart/', views.update_item_from_cart, name="update-from-cart"),
   path('checkout/<oid>/', views.checkout, name="checkout"),
   
   path('save-checkout-info/', views.save_checkout_infor, name="save-checkout-infor"),
   #paypal integration
   path('paypal/', include('paypal.standard.ipn.urls')),
   
   #thanh toan
   path('payment-completed/<oid>/', views.payment_completed_view, name="payment-completed"),
   path('payment-failed/', views.payment_failed_view, name="payment-failed"),
   path('dashboard/', views.dashboard_view, name="dashboard"),
   path('dashboard/order/<int:id>/', views.order_detail, name="order-detail"),
   path('make-default-address/', views.make_address_default, name="make-default-address"),
   path('wishlist/', views.wishlist_view, name="wishlist"),
   path('add-to-wishlist/', views.add_to_wishlist, name="add-to-wishlist"),
   path('remove-from-wishlist/', views.remove_wishlist, name="remove-from-wishlist"),
   path('contact/', views.contact, name="contact"),
   path('ajax-contact-form/', views.ajax_contact, name="contact-form")
   
]

e_comerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include('userauths.urls')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
    path("useradmin/", include("useradmin.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

useradmin/urls.py
from django.urls import path
from useradmin import views

app_name="useradmin"


urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("products/", views.product, name="products"),
    path("add-product/", views.add_product, name="add-product"),
    path("edit-product/<pid>/", views.edit_product, name="edit-product"),
    path("delete-product/<pid>/", views.delete_product, name="delete-product"),
    
]

useradmin/models.py
from django.db import models

# Create your models here.

useradmin/forms.py
from core.models import Product
from django import forms 

class AddProductForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Tên sản phẩm", "class": "form-control"}))
    description = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Mô tả", "class": "form-control"}))
    price = forms.CharField(widget=forms.NumberInput(attrs={"placeholder": "Giá...", "class": "form-control"}))
    old_price = forms.CharField(widget=forms.NumberInput(attrs={"placeholder": "Giá cũ..", "class": "form-control"}))
    stock_count = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Số lượng sản phẩm hiện có", "class": "form-control"}))
    updated= forms.DateTimeField(widget=forms.DateTimeInput(attrs={"placeholder": "Ngày cập nhật...", "class": "form-control"}))
    tags = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Gán nhãn hashtag ví dụ: #cream", "class": "form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class": "form-control"}))

    
    
    class Meta:
        model = Product
        
        fields = [
            "title",
            "sku",
            "description",
            "vendor",
            "price",
            "old_price",
            "specifications",
            "tags",
            "image",
            "product_status",
            "in_stock",
            "digital",
            "stock_count",
            "updated",
            "pid",
            "status",
            "featured",
            "category",
        ]

useradmin/views.py
from django.shortcuts import render, redirect
from core.models import CartOrder, Product, Category, Vendor
from django.db.models import Sum
from userauths.models import User
import datetime
from useradmin.forms import AddProductForm
from django.contrib import messages
# Create your views here.

def dashboard(request):
    revenue = CartOrder.objects.aggregate(price=Sum("price"))
    total_orders_count = CartOrder.objects.all()
    all_products = Product.objects.all()
    all_categories = Category.objects.all()
    new_customers = User.objects.all().order_by("-id")
    latest_orders = CartOrder.objects.all()
    
    this_month = datetime.datetime.now().month
    monthly_revenue = CartOrder.objects.filter(order_date__month=this_month).aggregate(price=Sum("price"))
    
    context = {
        "revenue": revenue,
        "total_orders_count": total_orders_count,
        "all_products": all_products,
        "all_categories": all_categories,
        "new_customers": new_customers,
        "latest_orders": latest_orders,
        "monthly_revenue": monthly_revenue,
        "this_month": this_month
    }
    
    return render(request, "useradmin/dashboard.html", context)


def product(request):
    all_products = Product.objects.all()
    all_categories = Category.objects.all()
    
    context = {
        "all_products": all_products,
        "all_categories": all_categories,
    }
    
    return render(request, "useradmin/product.html", context)


def add_product(request):
    form = AddProductForm()
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        print("sau hon")
        if form.is_valid():
           new_form = form.save(commit=False)
           
           new_form.user = request.user
           new_form.save()
           form.save_m2m()
           print("sau hon nua")
           return redirect("useradmin:dashboard")
        else:
           print(form.errors)
    else: 
        print("form k co gi ngoai cung")
        
    context = {
        "form" : form,
    }
    
    return render(request, "useradmin/add-product.html", context)


def edit_product(request, pid):
    product = Product.objects.get(pid=pid)
    form = AddProductForm()
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES, instance=product)
        print("sau hon")
        if form.is_valid():
           new_form = form.save(commit=False)
           
           new_form.user = request.user
           new_form.save()
           form.save_m2m()
           messages.success(request, "Sản phẩm cập nhật thành công! Vui lòng xem lại thông tin đã cập nhật")
           return redirect("useradmin:edit-product", product.pid)
        else:
           print(form.errors)
    else: 
        form = AddProductForm(instance=product)
        
    context = {
        "form" : form,
        "product": product
    }
    
    return render(request, "useradmin/edit-product.html", context)


def delete_product(request, pid):
    product = Product.objects.get(pid=pid)
    
    product.delete()
    
    return redirect("useradmin:products")

templates/useradmin/add-product.html
{% extends "partial/base.html" %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .form-container {
            max-width: 600px;
            margin: auto;
            background: #d1e0d5;
            border-radius: 10px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input,
        .form-group select {
            width: 90%;
            padding: 8px;
            box-sizing: border-box;
            margin-left: 20px;
        }
        .form-group input[type="file"] {
            padding: 3px;
        }
        .form-group input[type="checkbox"] {
            margin-right: 10px;
        }
        .form-group button {
            padding: 10px 15px;
            border: none;
            background-color: #007bff;
            color: white;
            cursor: pointer;
            border-radius: 5px;

        }
        .form-group button:hover {
            background-color: #0056b3;
        }
        .indent-2{
            margin-left: 20px;
        }
        .indent-5{
            margin-left: 150px;
        }
        

    </style>
</head>
    <div class="form-container" >
        <h1 class="indent-5">Thêm sản phẩm</h1>
        <form acction=""method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.error %}
            <p>Loi form</p>
            {% endif %}
            <div class="form-group">
                <label class="indent-2">Mã sku</label>
                {{form.sku}}
            </div>
            <div class="form-group">
                <label class="indent-2">Mã sản phẩm</label>
                {{form.pid}}
            </div>
            <div class="form-group">
                <label class="indent-2">Tên sản phẩm</label>
                {{form.title}}
            </div>
            <div class="form-group">
                <label class="indent-2">Mô tả</label>
                {{form.description}}
            </div>
            <div class="form-group">
                <label class="indent-2">Nhà cung cấp</label>
                    {{form.vendor}}
            </div>
            <div class="form-group">
                <label class="indent-2">Giá</label>
                {{form.price}}
            </div>
            <div class="form-group">
                <label class="indent-2">Giá cũ</label>
                {{form.old_price}}
            </div>
            <div class="form-group">
                <label class="indent-2">Điểm nổi bật</label>
                <div class="indent-2">{{form.specifications}}</div>
            </div>
            <div class="form-group">
                <label class="indent-2">Tags</label>
                {{form.tags}}
            </div>

            <div class="form-group">
                <label class="indent-2">Hình ảnh</label>
                {{form.image}}
                <img src="https://cdn-icons-png.freepik.com/256/14682/14682609.png?semt=ais_hybrid" class="indent-2" style="height: 100px; width: 100px;" >
            </div>

            <div class="form-group">
                <label class="indent-2">Tình trạng</label>
                {{form.product_status}}
            </div>
            <div class="form-group">
                <label class="indent-2">Sẵn sàng bán</label>
                {{form.status}}
            </div>
            <div class="form-group">
                <label class="indent-2">featured</label>
                {{form.featured}}
            </div>
            <div class="form-group">
                <label class="indent-2">Trong kho</label>
                    {{form.in_stock}}
            </div>
            <div class="form-group">
                <label class="indent-2">Hàng điện tử</label>
                {{form.digital}}
            </div>
            <div class="form-group">
                <label class="indent-2">Thực tế</label>
                {{form.stock_count}}
            </div>
            <div class="form-group">
                <label class="indent-2">Ngày cập nhật</label>
                {{form.updated}}
            </div>
           
                <div class="form-group">
                    <label class="indent-2">Phân loại</label>
                            {{form.category}}
                </div>
                <div class="form-group">
                    <button type="submit" >Tạo sản phẩm</button>
                </div>
        </form>
    </div>

    {% endblock content %}

templates/useradmin/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vendor Dashboard</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            
        }
        .header {
            background-color: #333;
            color: #fff;
            padding: 10px 20px;
            text-align: center;
        }
        .container {
            display: flex;
        }
        .sidebar {
            width: 200px;
            background-color: #333;
            color: #fff;
            padding: 20px;
            height: 100vh;
            position: fixed;
            top: 0;
            left: 0;
        }
        .sidebar a {
            color: #fff;
            text-decoration: none;
            display: block;
            padding: 10px 0;
            border-bottom: 1px solid #444;
        }
        .sidebar a:hover {
            background-color: #575757;
        }
        .main-content {
            margin-left: 250px;
            padding: 20px;
            flex: 1;
        }
        .card {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-bottom: 20px;
        }
        .card h2 {
            margin-top: 0;
        }
        .custom {
            height: 100px;
            width: 220px;
            background: #fafbfd;
            margin-left: 15px;
            text-align: center;
            
        }
        .icon {
            float: left;
            position: absolute;
        }
        
        .div-content {
            clear: both;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }
        
        th, td {
            text-align: center;
            padding: 8px;
        }
        
        th {
            background-color: #f2f2f2;
        }
        
        tr:nth-child(even) {
            background-color:   
         #f2f2f2;
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

    <div class="header">
        <h1>Xin chào!</h1>
    </div>

    <div class="container">
        <div class="sidebar">
            <h2>Chế độ xem</h2>
            <a href="#overview">Tổng Quan</a>
            <a href="#orders">Orders</a>
            <a href="{% url "useradmin:products" %}">Sản phẩm</a>
            <a href="{% url "useradmin:add-product" %}">Thêm sản phẩm</a>
            <a href="#settings">Settings</a>
        </div>

        <div class="main-content">
            <div class="card" id="overview">
                <h2>Overview</h2>

                <p>Welcome to your dashboard. Here you can get an overview of your current status, recent activities, and important updates.</p>
            </div>
            
            <div class="card" id="orders">
                <h2>Orders</h2>
                <table>
                    <td>
                        <div class="custom">
                            <i class="fa-solid fa-hand-holding-dollar fa-2xl" style="color: #c93131;"></i>
                            <p>Lợi nhuận</p>
                            <p>{{revenue.price|floatformat:0}} VND</p>
                        </div>
                    </td>
                    <td>
                        <div class="custom">
                            <i class="fa-solid fa-truck-fast fa-2xl " style="color: #163160;"></i>
                            <p>Đơn hàng</p>
                            <p>{{total_orders_count.count}}</p>
                        </div>
                        
                    </td>
                    <td>
                        <div class="custom">
                            <i class="fa-solid fa-briefcase fa-2xl" style="color: #5d0995;"></i>
                            <p>Sản phẩm</p>
                            <p>{{all_products.count}}</p>
                        </div>
                    </td>
                    <td>
                        <div class="custom">
                            <i class="fa-solid fa-shapes fa-2xl" style="color: #5c9226;"></i>
                            <p>Tổng tháng</p>
                        <p>{{monthly_revenue.price|floatformat:0}} VND</p>
                        </div>
                    </td>
                </table>
            </div>
            
            <div class="card" id="products">
                <h2>Chi tiết đơn hàng tháng {{this_month}}</h2>
            <table>
                <thead>
                    <tr>
                        <th>Đơn hàng</th>
                        <th>Ngày Đặt</th>
                        <th>Người đặt</th>
                        <th>Số điện thoại</th>
                        <th>Tổng tiền</th>
                        <th>Chi tiết</th>

                    </tr>
                </thead>
                <tbody>
                    {% for order in latest_orders %}
                    <tr>
                        <td>#{{order.oid}}</td>
                        <td>{{order.order_date}}</td>
            
                        <td>{{order.fullname}}</td>
                       
                        <td>{{order.phone}}</td>
                        
                        <td>{{order.price|floatformat:0}}</td>
                        <td><a href="">Chi tiết tại</a></td>

                        
                    </tr>
                    {% endfor %}
                    <!-- More rows as needed -->
                </tbody>
            </table>
            </div>
            
            <div class="card" id="reports">
                <h2>Reports</h2>
                <p>View various reports related to sales, performance, and other metrics.</p>
            </div>
            
            <div class="card" id="settings">
                <h2>Settings</h2>
                <p>Configure your account settings, preferences, and other configurations.</p>
            </div>
        </div>
    </div>

</body>
</html>

templates/useradmin/edit-product.html
{% extends "partial/base.html" %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .form-container {
            max-width: 600px;
            margin: auto;
            background: #d1e0d5;
            border-radius: 10px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input,
        .form-group select {
            width: 90%;
            padding: 8px;
            box-sizing: border-box;
            margin-left: 20px;
        }
        .form-group input[type="file"] {
            padding: 3px;
        }
        .form-group input[type="checkbox"] {
            margin-right: 10px;
        }
        .form-group button {
            padding: 10px 15px;
            border: none;
            background-color: #007bff;
            color: white;
            cursor: pointer;
            margin-bottom: 10px;
            margin-left: 5px;
            border-radius: 5px;

        }
        .form-group button:hover {
            background-color: #0056b3;
        }
        .indent-2{
            margin-left: 20px;
        }
        .indent-5{
            margin-left: 150px;
        }
        .color-render{
            margin-left: 300px;
            padding: 10px 15px;
            border: none;
            background-color: #007bff;
            color: white;
            border-radius: 5px;

        }
    </style>
</head>
    <div class="form-container" >
        <h1 class="indent-5">Cập nhật sản phẩm</h1>
        <form acction=""method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.error %}
            <p>Loi form</p>
            {% endif %}
            <div class="form-group">
                <label class="indent-2">Mã sku</label>
                {{form.sku}}
            </div>
            <div class="form-group">
                <label class="indent-2">Mã sản phẩm</label>
                {{form.pid}}
            </div>
            <div class="form-group">
                <label class="indent-2">Tên sản phẩm</label>
                {{form.title}}
            </div>
            <div class="form-group">
                <label class="indent-2">Mô tả</label>
                {{form.description}}
            </div>
            <div class="form-group">
                <label class="indent-2">Nhà cung cấp</label>
                    {{form.vendor}}
            </div>
            <div class="form-group">
                <label class="indent-2">Giá</label>
                {{form.price}}
            </div>
            <div class="form-group">
                <label class="indent-2">Giá cũ</label>
                {{form.old_price}}
            </div>
            <div class="form-group">
                <label class="indent-2">Điểm nổi bật</label>
                <div class="indent-2">{{form.specifications}}</div>
            </div>
            <div class="form-group">
                <label class="indent-2">Tags</label>
                {{form.tags}}
            </div>

            <div class="form-group">
                <label class="indent-2">Hình ảnh</label>
                {{form.image}}
                <img src="{{product.image.url}}" class="indent-2" style="height: 100px; width: 100px;" >
            </div>

            <div class="form-group">
                <label class="indent-2">Tình trạng</label>
                {{form.product_status}}
            </div>
            <div class="form-group">
                <label class="indent-2">Sẵn sàng bán</label>
                {{form.status}}
            </div>
            <div class="form-group">
                <label class="indent-2">featured</label>
                {{form.featured}}
            </div>
            <div class="form-group">
                <label class="indent-2">Trong kho</label>
                    {{form.in_stock}}
            </div>
            <div class="form-group">
                <label class="indent-2">Hàng điện tử</label>
                {{form.digital}}
            </div>
            <div class="form-group">
                <label class="indent-2">Thực tế</label>
                {{form.stock_count}}
            </div>
            <div class="form-group">
                <label class="indent-2">Ngày cập nhật</label>
                {{form.updated}}
            </div>
           
                <div class="form-group">
                    <label class="indent-2">Phân loại</label>
                            {{form.category}}
                </div>
                <div class="form-group">
                    <button type="submit" >Cập nhật sản phẩm</button>
                    <a class="color-render" href="{% url "useradmin:products" %}"><i class="fa-solid fa-arrow-left fa-xl" style="color: #e51f1f;"></i> Quay lại</a>
                </div>
        </form>
    </div>

    {% endblock content %}

templates/useradmin/product.html
{% extends "partial/base.html" %}
{% block content %}
<div class="col-lg-8 table-responsive mb-5"  style="margin: 0 auto;">
    <table class="table table-light table-borderless table-hover text-center mb-0">
        <thead class="thead-dark">
            <tr>
                <th>Hình ảnh</th>
                <th>Sản phẩm</th>
                <th>Giá</th>
                <th>Trạng thái</th>
                <th>Ngày đăng bán</th>
                <th>Cập nhật</th>
                <th>Loại bỏ</th>
            </tr>
        </thead>
        <p>Sản phẩm</p>
        <tbody class="align-middle" id="wishlist-list">
            {% for product in all_products %}
            <tr class="tr-row-1">
                <td class="align-middle"><img  src="{{product.image.url}}"  alt="" style="width: 50px; height: 50px;"></td>
                <td class="align-middle">{{product.title}}</td>
                <td class="align-middle">{{product.price}}</td>
                <td class="align-middle"><a href="{% url "core:product-list" %}">{{product.product_status}}</a></td>
                <td class="align-middle">{{product.date}}</td>
                <td class="align-middle"><a href="{% url "useradmin:edit-product" product.pid %}" title="Edit product"><i class="fa-solid fa-arrow-up-from-bracket fa-xl" style="color: #2d8f0a;"></i></a></td>
                <td class="align-middle"><a href="{% url "useradmin:delete-product" product.pid %}"><i class="fa-solid fa-trash fa-xl" style="color: #e60a0a;"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}