core/urls.py
from django.urls import path, include
from core import views

app_name ="core"

urlpatterns = [
   path('', views.index, name='index'),
   path('products/', views.product_list_view, name='product-list'),
   path('categories/', views.category_list_view, name='category-list'),
   path('category_product/<cid>/', views.category_product_list, name='category-product-list'),
   path('vendor_list/', views.vendor_list_view, name="vendor-list"),
   path('product_detail/<pid>/', views.product_detail_view, name='product-detail'),
   path('product/tags/<slug:tag_slug>/', views.tag_list, name='tags'),
   path('ajax-add-review/<int:pid>/', views.ajax_add_review, name="ajax-add-review"),
   path('search/', views.search_view, name='search'),
   path('filter-products/', views.filter_product, name="filter-products"),
   path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
   path('cart/', views.cart_view, name="cart"),
   path('delete-from-cart/', views.delete_item_from_cart, name="delete-from-cart"),
   path('update-from-cart/', views.update_item_from_cart, name="update-from-cart"),
   path('checkout/<oid>/', views.checkout, name="checkout"),
   
   path('save-checkout-info/', views.save_checkout_infor, name="save-checkout-infor"),
   #paypal integration
   path('paypal/', include('paypal.standard.ipn.urls')),
   
   #thanh toan
   path('payment-completed/<oid>/', views.payment_completed_view, name="payment-completed"),
   path('payment-failed/', views.payment_failed_view, name="payment-failed"),
   path('dashboard/', views.dashboard_view, name="dashboard"),
   path('dashboard/order/<int:id>/', views.order_detail, name="order-detail"),
   path('make-default-address/', views.make_address_default, name="make-default-address"),
   path('wishlist/', views.wishlist_view, name="wishlist"),
   path('add-to-wishlist/', views.add_to_wishlist, name="add-to-wishlist"),
   path('remove-from-wishlist/', views.remove_wishlist, name="remove-from-wishlist"),
   path('contact/', views.contact, name="contact"),
   path('ajax-contact-form/', views.ajax_contact, name="contact-form")
   
]

e_comerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include('userauths.urls')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
    path("useradmin/", include("useradmin.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewFrom(forms.ModelForm):
    
    review = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Vui lòng đánh giá..."}))
    
    class Meta:
        model = ProductReview
        fields = ['review', 'rating']
        

core/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from core.models import Category, Product, Vendor, CartOrder, CartOrderItem, WishList, Address, ProductImage, ProductReview
from taggit.models import Tag
from django.db.models import Avg, Count
from core.forms import ProductReviewFrom
from django.template.loader import render_to_string
# import thu vien can thiet cho paypal
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
import datetime
from django.core import serializers
import calendar
from django.db.models.functions import ExtractMonth, ExtractYear
from userauths.models import ContactUs

# Create your views here.
def index(request):
    products = Product.objects.all().order_by('-id')
    context = {
        'products': products,
    }
    return render(request, 'core/index.html', context)

def product_list_view(request):
    products = Product.objects.filter(product_status="published")
    context = {
        'products': products,
    }
    return render(request, 'core/product-list.html', context)


def category_list_view(request):
    categories = Category.objects.all()
    
    context = {
        'categories': categories
    }
    
    return render(request, 'core/category-list.html', context)


def category_product_list(request, cid):
    
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category=category)
    
    context = {
        'category': category,
        'products': products
    }
    
    return render(request, 'core/category_product_list.html', context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        'vendors': vendors
    }
    return render(request, 'core/vendor_list.html', context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    p_image = product.p_images.all()
    products = Product.objects.filter(category=product.category).exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product).order_by('-date')
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    review_form = ProductReviewFrom()
    
    make_review = True
    user_review_count = 0    
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
    
    if user_review_count > 0:
        make_review = False
    
    context = {
        "products": product,
        "product" : products,
        'p_image' : p_image,
        'reviews' : reviews,
        'average_rating': average_rating,
        'review_form': review_form,
        'make_review': make_review
    }
    return render(request, 'core/product_detail.html', context)

def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status = "published")
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
        
    context ={
        'products':products,
        'tag':tag
    }
    
    return render(request, 'core/tag.html', context)


def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user
    
    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )
    
    context = {
        'user':user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating']
    }
    
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    
    result =  JsonResponse(
        {
            'bool': True,
            'context': context,
            'average_reviews': average_reviews
        }
    )

    
    return result


def search_view(request):
    
    query = request.GET.get('search')
    products = Product.objects.filter(title__icontains=query).order_by('-date')
    
    context = {
        'products': products,
        'query': query
    }
    
    return render(request, 'core/search.html', context)


def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')
    
    products = Product.objects.filter(product_status="published").order_by("-id").distinct()
    
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']
    
    products = products.filter(price__gte = min_price)
    products = products.filter(price__lte = max_price)
    
    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()
        
    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()
        
    data = render_to_string("core/async/product-list.html", {'products': products})
    
    return JsonResponse(
        {
            "data" : data,
        }
    )
    
def add_to_cart(request):
    cart_product = {}
        
    cart_product[request.GET['id']] = {
        'title':request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image':request.GET.getlist('image'),
        'pid': request.GET.getlist('pid'),
    }
    
    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            
            request.session['cart_data_obj'] = cart_data
            
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product
        
    return JsonResponse({
        "data": request.session['cart_data_obj'],
        "totalCartItems": len(request.session['cart_data_obj'])
    })
    
    
def cart_view(request):
    
    
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price']) if item['price'] else 0
            
        return render(request,  "core/cart.html", {"cart_data": request.session['cart_data_obj'], 'totalCartItems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
    
    else:
        
        return render(request,  "core/cart.html", {"cart_data":"", 'totalCartItems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
        

def delete_item_from_cart(request):
    
    product_id = str(request.GET.get('id'))
    
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
            
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price']) if item['price'] else 0
        
    context = render_to_string("core/async/cart-list.html",{"cart_data": request.session['cart_data_obj'], 'totalCartItems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount} )
        
    return JsonResponse({
        "data" : context,
        'totalCartItems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount
    })
    

def update_item_from_cart(request):
    
    product_id = str(request.GET.get('id'))
    product_qty = str(request.GET.get('qty'))
    
    
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET.get('id'))]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data
            
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price']) if item['price'] else 0
        
    context = render_to_string("core/async/cart-list.html",{"cart_data": request.session['cart_data_obj'], 'totalCartItems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount} )
        
    return JsonResponse({
        "data" : context,
        'totalCartItems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount
    })
    
    
def save_checkout_infor(request):
    cart_total_amount = 0
    total_amount = 0
    
    if request.method == "POST":
        full_name = request.POST.get("fullname")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        address = request.POST.get("address")
        state = request.POST.get("state")
        zipcode  = request.POST.get("zipcode")
        
        request.session['fullname'] = full_name
        request.session['email'] = email
        request.session['phone'] = phone
        request.session['address'] = address
        request.session['state'] = state
        request.session['zipcode'] = zipcode
        
        if 'cart_data_obj' in request.session:
            for p_id, item in request.session['cart_data_obj'].items():
                total_amount += int(item['qty']) * float(item['price']) if item['price'] else 0

templates/core/checkout.html
{% extends "partial/base.html" %}
{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url "core:index" %}">Trang chủ</a>
                    <a class="breadcrumb-item text-dark" href="{% url "core:product-list" %}">Mua sắm</a>
                    <span class="breadcrumb-item active">Kiểm tra</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Checkout Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Địa chỉ thanh toán</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label>Tên người dùng</label>
                            <input class="form-control" type="text" value="{{order.user}}">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Số điện thoại</label>
                            <input class="form-control" type="text" value="{{order.phone    }}" >
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Địa chỉ</label>
                            <input class="form-control" type="text" value="{{order.address}}">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Email</label>
                            <input class="form-control" type="text" value="{{order.email}}">
                        </div>
                    </div>
                </div>
 
            </div>
            <div class="col-lg-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Thanh Toán</span></h5>
                <div class="bg-light p-30 mb-5" >
                    <div class="border-bottom">

                        <table class="table table-light table-borderless table-hover text-center mb-0">
                            <thead class="thead-dark">
                                <tr>
                                    <th>S.Phẩm</th>
                                    <th>Giá</th>
                                    <th>Số lượng</th>
                                    <th>H.Ảnh</th>
                                </tr>
                            </thead>
                            <tbody class="align-middle">
                                {% for order_item in order_items %}
                                <tr>
                                    <td class="align-middle">{{order_item.item}}</td>
                                    <td class="align-middle">{{order_item.price|floatformat:0}}</td>
                                    <td class="align-middle">
                                        <div class="input-group quantity mx-auto" style="width: 100px;">
                                            <p class="form-control form-control-sm bg-secondary border-0 text-center">x{{order_item.quantity}}</p>
                                            <div class="input-group-btn">
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle"><img src="{{order_item.image}}" alt="" style="width: 40px; height: 40px;"></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    
                    </div>
                    <div class="border-bottom pt-3 pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Tổng tiền</h6>
                            <h6>{{order.price|floatformat:0}} đồng</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Vận chuyển</h6>
                            <h6 class="font-weight-medium">0 đồng</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Tất cả</h5>
                            <h5>{{order.price|floatformat:0}} đồng</h5>
                        </div>
                    </div>
                </div>
                <div class="mb-5">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Payment</span></h5>
                    <div class="bg-light p-30">
                        <div class="form-group">
                            <div class="custom-control custom-radio" id="paypal-button-container">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="directcheck">
                                <label class="custom-control-label" for="directcheck">Direct Check</label>
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <div class="custom-control custom-radio" >
                                <input type="radio" class="custom-control-input" name="payment" id="banktransfer">
                                <label class="custom-control-label" for="banktransfer">Bank Transfer</label>
                            </div>
                        </div>
                        <div style="margin-top: 20px;" id="paypal-button-container">
                        </div>

                        <!--<button class="btn btn-block btn-primary font-weight-bold py-3">Place Order</button>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Checkout End -->

    <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  
    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            style: {
                color:  'blue',
                shape:  'pill',
                label:  'pay',
                height: 40
            },
            
            // Call your server to set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
					purchase_units: [{
						amount: {
							value :{{order.price}},
						}
					}]
				})
            },

            // Call your server to finalize the transaction
            onApprove: function(data, actions) {
               return actions.order.capture().then(function(details){
                if (details.status === "COMPLETED"){
                    window.location.href = `/payment-completed/{{order.oid}}/?status=${details.status}`
                }
			   })
            }

        }).render('#paypal-button-container');
    </script>

    {% endblock content %}

templates/core/product-list.html
{% extends "partial/base.html" %}
{% load static %}
<head>
    <style>
        input[type="range"]{
            -webkit-appearance: none;
            margin-right: 15px;
            height: 7px;
            width: 220px;
            background: rgba(255, 255, 255, 0.6);
            border-radius: 5px;
            background-image: linear-gradient(#3bb77e, #3bb77e);
            background-size: 100% 100%;
            background-repeat: no-repeat;
        }
        input[type="range"]::-webkit-slider-thumb{
            -webkit-appearance: none;
            width: 20px;
            height: 20px;
            border-radius: 50%;
            background: #3bb77e;
            cursor: ew-resize;
            box-shadow: 0 0 2px 0 #555;
            transition: background .3e ease-in-out;
        }
        input[type=range]::-webkit-slider-runnable-track{
            -webkit-appearance: none;
            box-shadow: none;
            border: none;
            background: transparent;
        }
        .filter-button {
            /* Các thuộc tính kiểu dáng cho nút */
            background-color: #4CAF50; /* Màu xanh lá cây */
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;   
          
            font-size: 16px;
            /* Căn giữa chữ trong nút */
            display: inline-block;
            text-align: center;
          }
          .btn {
            display: block;
            margin: 0 auto;
          }
          .cnt{
            height: 75px;
            width: 220px;
            padding: 0px 0px 10px 10px;
            color: #CC9900;
          }
    </style>
</head>
{% block content %}



    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url "core:index" %}">Trang chủ</a>
                    <span class="breadcrumb-item active">Sản phẩm</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4">
                <!-- Price Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Lọc theo loại</span></h5>
                <div class="bg-light p-4 mb-30">
                        {% for category in categories %}
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" data-filter="category" class="custom-control-input filter-checkbox" id="catergorycheck{{category.id}}" name="checkbox" value="{{category.id}}">
                            <p class="custom-control-label" for="categorycheck{{category.id}}">{{category.title}}</p>
                        </div>
                        {% endfor %}    
                </div>
                <!-- Price End -->
                
                <!-- Color Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Theo nhà phân phối</span></h5>
                <div class="bg-light p-4 mb-30">
                   {% for vendor in vendors %}
                       <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3" >

                            <input type="checkbox" name="checkbox" data-filter="vendor" class="custom-control-input filter-checkbox" id="vendorcheck{{vendor.id}}" value ="{{vendor.id}}">
                            <p class="custom-control-label" for="vendorcheck{{vendor.id}}">{{vendor.title}}</p>
                     
                        </div>
                        {% endfor %}
                </div>
                <!-- Color End -->

                <!-- Size Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Lọc theo giá</span></h5>
                <div class="bg-light p-4 mb-30 ">
                   <input type="range" name="ranDge" class="range-slider" id="range" min="{{min_max_price.price__min|floatformat:1}}" max="{{min_max_price.price__max|floatformat:1}}" oninput="max_price.value=this.value" >
                    <div>
                        <input type="number" name="" class="cnt" id="max_price" placeholder="Giá hiện tại" min="{{min_max_price.price__min}}" max="{{min_max_price.price__max}}" onkeyup="range.value=this.value" >
                    </div>
                   <div class="d-flex justify-content-between">
                    
                   <div class="caption">Từ: <strong id="slider-range-value1" class="text">{{min_max_price.price__min|floatformat:1}}VND</strong></div>
                   <div class="caption">Đến: <strong id="slider-range-value2" class="text">{{min_max_price.price__max|floatformat:1}} VND</strong></div>

                   </div>
                   <div class="button-checkbox">
                    <button class=" btn filter-button" type="button" id="btn-filter-check">Lọc</button>
                </div>
                </div>
                <!-- Size End -->
            </div>
            <!-- Shop Sidebar End -->


            <!-- Shop Product Start -->
            <div class="col-lg-9 col-md-8">
                <div class="row pb-3" id="filterd-product">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div>
                                <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                                <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                            </div>
                            <div class="ml-2">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">Sorting</button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">Latest</a>
                                        <a class="dropdown-item" href="#">Popularity</a>
                                        <a class="dropdown-item" href="#">Best Rating</a>
                                    </div>
                                </div>
                                <div class="btn-group ml-2">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">Showing</button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">10</a>
                                        <a class="dropdown-item" href="#">20</a>
                                        <a class="dropdown-item" href="#">30</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    {% for product in products %}
                    <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                        
                        <div class="product-item bg-light mb-4">
                            
                            <div class="product-img position-relative overflow-hidden" class="col-lg-4 col-md-6 col-sm-6 pb-1">
                                <div style="width: 290px; height: 270px;" >
                                    <img class="img-fluid w-100" src='{{product.image.url}}'  alt="">
                                    </div>
                                <div class="product-action">
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href="{% url "core:product-detail" product.pid %}"><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate" href="">{{product.title}}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <h5>{{product.price}}</h5><h6 class="text-muted ml-2"><del>{{product.old_price}}</del></h6>
                                </div>
                                <div class="d-flex align-items-center justify-content-center mb-1">
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small>(99)</small>
                                </div>

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                   
                    <div class="col-12">
                        <nav>
                          <ul class="pagination justify-content-center">
                            <li class="page-item disabled"><a class="page-link" href="#">Trang trước</span></a></li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">Trang sau</a></li>
                          </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->



    {% endblock content %}