core/urls.py
from django.urls import path, include
from core import views

app_name ="core"

urlpatterns = [
   path('', views.index, name='index'),
   path('products/', views.product_list_view, name='product-list'),
   path('categories/', views.category_list_view, name='category-list'),
   path('category_product/<cid>/', views.category_product_list, name='category-product-list'),
   path('vendor_list/', views.vendor_list_view, name="vendor-list"),
   path('product_detail/<pid>/', views.product_detail_view, name='product-detail'),
   path('product/tags/<slug:tag_slug>/', views.tag_list, name='tags'),
   path('ajax-add-review/<int:pid>/', views.ajax_add_review, name="ajax-add-review"),
   path('search/', views.search_view, name='search'),
   path('filter-products/', views.filter_product, name="filter-products"),
   path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
   path('cart/', views.cart_view, name="cart"),
   path('delete-from-cart/', views.delete_item_from_cart, name="delete-from-cart"),
   path('update-from-cart/', views.update_item_from_cart, name="update-from-cart"),
   path('checkout/<oid>/', views.checkout, name="checkout"),
   
   path('save-checkout-info/', views.save_checkout_infor, name="save-checkout-infor"),
   #paypal integration
   path('paypal/', include('paypal.standard.ipn.urls')),
   
   #thanh toan
   path('payment-completed/<oid>/', views.payment_completed_view, name="payment-completed"),
   path('payment-failed/', views.payment_failed_view, name="payment-failed"),
   path('dashboard/', views.dashboard_view, name="dashboard"),
   path('dashboard/order/<int:id>/', views.order_detail, name="order-detail"),
   path('make-default-address/', views.make_address_default, name="make-default-address"),
   path('wishlist/', views.wishlist_view, name="wishlist"),
   path('add-to-wishlist/', views.add_to_wishlist, name="add-to-wishlist"),
   path('remove-from-wishlist/', views.remove_wishlist, name="remove-from-wishlist"),
   path('contact/', views.contact, name="contact"),
   path('ajax-contact-form/', views.ajax_contact, name="contact-form")
   
]

e_comerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include('userauths.urls')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
    path("useradmin/", include("useradmin.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name ='userauths'

urlpatterns = [
    path('sign-up/', views.register_view, name="sign-up"),
    path('sign-in/', views.login_view, name="sign-in"),
    path('sign-out/', views.logout_view, name="sign-out")
    
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.username
    
    
class ContactUs(models.Model):
    
    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=150)
    phone = models.CharField(max_length=20)
    subject = models.CharField(max_length=50)
    message = models.TextField()
    
    class Meta:
        verbose_name = "Liên hệ"
        verbose_name_plural = "Contact"
    
    def __str__(self):
        return self.full_name

    

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))
    password1 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'password'}))
    password2 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'repeat password'}))
    
    class Meta:
        model = User
        fields = ['username','email']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import logout
from userauths.models import User

# User = settings.AUTH_USER_MODEL

# Create your views here.
def register_view(request):
    
    form = UserRegisterForm(request.POST or None)
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Chào {username},tài khoản được tạo thành công")
            new_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'] )
            login(request, new_user)
            return redirect('core:index')
   
    context = {
        'form' : form
    }
    return render(request, 'userauths/sign-up.html', context)

def login_view(request):
    

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email = email)
            user = authenticate(request, email = email, password = password)
            if user is not None:
                login(request, user)
                messages.success(request, "Đăng nhập thành công") 
                return redirect("core:index")
            else:
                messages.warning(request, "Email hoặc mật khẩu không chính xác")
        except:
            messages.warning(request, f"{email} không tồn tại")
        
        
        
    context = {}
    
    if request.user.is_authenticated:
        
        return redirect('core:index')
    
    
    return render(request, 'userauths/sign-in.html', context)


def logout_view(request):
    logout(request)
    messages.success(request, "Đã đăng xuất")
    
    return redirect('userauths:sign-in')

templates/userauths/sign-in.html
{% extends "partial/base.html" %}
{% block content %}
<section class="vh-100">
    <div class="container py-5 h-100">
      <div class="row d-flex align-items-center justify-content-center h-100">
        <div class="col-md-8 col-lg-7 col-xl-6">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
            class="img-fluid" alt="Phone image">
        </div>
        <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
          <form method="POST">
            {% csrf_token %}
            <!-- Email input -->
            <div data-mdb-input-init class="form-outline mb-4">
              <input type="email" id="form1Example13" name="email" class="form-control form-control-lg" />
              <label class="form-label" for="form1Example13">Email address</label>
            </div>
  
            <!-- Password input -->
            <div data-mdb-input-init class="form-outline mb-4">
              <input type="password" id="form1Example23" name="password" class="form-control form-control-lg" />
              <label class="form-label" for="form1Example23">Password</label>
            </div>
  
            <div class="d-flex justify-content-around align-items-center mb-4">
              <!-- Checkbox -->
              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="form1Example3" checked />
                <label class="form-check-label" for="form1Example3"> Remember me </label>
              </div>
              <a href='{% url "userauths:sign-up" %}'>Chưa có tài khoản?</a>
            </div>
  
            <!-- Submit button -->
            <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg btn-block">Đăng Nhập</button>
  
            {% comment %} <div class="divider d-flex align-items-center my-4">
              <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
            </div>
  
            <a data-mdb-ripple-init class="btn btn-primary btn-lg btn-block" style="background-color: #3b5998" href="#!"
              role="button">
              <i class="fab fa-facebook-f me-2"></i>Continue with Facebook
            </a>
            <a data-mdb-ripple-init class="btn btn-primary btn-lg btn-block" style="background-color: #55acee" href="#!"
              role="button">
              <i class="fab fa-twitter me-2"></i>Continue with Twitter</a> {% endcomment %}
  
          </form>
        </div>
      </div>
    </div>
  </section>
  {% endblock content %}

templates/userauths/sign-up.html
{% extends "partial/base.html" %}
{% block content %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
  
                  <form class="mx-1 mx-md-4" method="POST">
                    {% csrf_token %}
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div data-mdb-input-init class="form-outline flex-fill mb-0">
                        <input type="text" id="form3Example3c" class="form-control" {{form.username}} 
                        {% comment %} <label class="form-label" for="form3Example1c">Your Name</label> {% endcomment %}
                        
                      </div>
                      
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div data-mdb-input-init class="form-outline flex-fill mb-0">
                        <input type="email" id="form3Example3c" class="form-control" {{form.email}} 
                        {% comment %} <label class="form-label" for="form3Example3c">Your Email</label> {% endcomment %}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div data-mdb-input-init class="form-outline flex-fill mb-0">
                        <input type="password" id="form3Example4c" class="form-control" {{form.password1}}
                        {% comment %} <label class="form-label" for="form3Example4c">Password</label> {% endcomment %}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div data-mdb-input-init class="form-outline flex-fill mb-0">
                        <input type="password" id="form3Example4cd" class="form-control" {{form.password2}}
                        {% comment %} <label class="form-label" for="form3Example4cd">Repeat your password</label> {% endcomment %}
                      </div>
                    </div>

                  <div class="form-check d-flex justify-content-center mb-5">
                    
                      <label class="form-check-label" for="form2Example3">
                        <p class="text-center h6 fw-bold mb-5 mx-1 mx-md-4 mt-4">Đã có tài khoản <a href="{% url "userauths:sign-in" %}">Đăng Nhập</a></p>
                      </label>
                    </div>   
                     

                   

                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg">Đăng ký</button>
                    </div>
                    {% if form.errors %}
                    <div class="alert alert-danger">
                      <strong>{{form.errors}}</strong>
                    </div>
                    {% endif %}
  
                  </form>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}